### ISSUE TITLE
How to set locale per goroutine?

### ISSUE THREAD

**Issue by jacek99** [gosexy/gettext#4]
I want to use this in a web app, where potentially every request comes in for a different locale.

The SetLocale() command seems to be global.

How do you handle this in case where an app is serving in multiple languages similtaneously, different locale per goroutine?

If this functionality already exists, please document how.

Thank you

**Comment by jacek99** [comment]
Thanks for any answers. I need to add internationalization to my project ASAP...

**Comment by xiam** [comment]
Hello @jacek99,

These are only wrappers around gettext, if gettext supports using multiple domains then it should be possible to support multiple languages with this wrapper as well.

Something like this should work for using different languages on the same app:

``` go
// Untested code

gettext.BindTextdomain("en_US", domainsDirectory)
gettext.BindTextdomain("es_MX", domainsDirectory)

gettext.TextDomain("en_US")

fmt.Println(gettext.DGettext("en_US", "Hello world!"))
fmt.Println(gettext.DGettext("es_MX", "Hello world!"))
```

If you want this to work with different locales per goroutine you should provide each goroutine with a context, so they "know" what domain to use. Could you test an confirm?
